{% set data = load_setup_py_data() %}

package:
  name: arrebol
  version: {{ data.get('version') }}

source:
  path: ../src

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - requests

about:
  home: https://github.com/traquitanas/arrebol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: sss
  description: |
    Teste do Pacote
  doc_url: https://github.com/traquitanas/arrebol
  dev_url: https://github.com/traquitanas/arrebol
