{% set data = load_setup_py_data() %}
#{% set name = "arrebol" %}
#{% set version = "1.0.8" %}

package:
  name: arrebol
  version: {{ data['__version__'] }}

source:
  path: ..

# Se usar o build aqui, com pip, não deve ser usando o arquivo build.sh (e setuptools).
build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --use-feature=in-tree-build -vv "

requirements:
  build:
    - python
    - setuptools
    - numpy>=1.11.1,<=1.16.0
    - conda-verify

#   host:
#     - pip
#     - python 3.6
#     - requests
#     - numpy>=1.11.1,<=1.16.0
    #- setuptools
    #- pycep_correios

  run:
    - python
    - numpy>=1.11.1,<=1.16.0
    - requests

test:
  imports:
    - {{ data['name'] }}

about:
  license: {{ data['license'] }}
  license_family: MIT
  license_file: LICENSE
  summary: {{ data['description'] }}
  description: |
    Teste do Pacote
  home: {{ data['url'] }}
  doc_url: https://github.com/traquitanas/arrebol
  dev_url: https://github.com/traquitanas/arrebol
