{% set version = "1.1.0" %}
#{% set data = load_setup_py_data() %}

package:
  name: arrebol
  #version: {{ data.get('version') }}
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - requests

  host:
    - python
    - setuptools
    - numpy
    - pip

  run:
    - python
    - setuptools
    - requests

about:
  home: https://github.com/traquitanas/arrebol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Descricao
  description: |
    Teste do Pacote
  doc_url: https://github.com/traquitanas/arrebol
  dev_url: https://github.com/traquitanas/arrebol
