{% set name = "arrebol" %}
{% set version = "1.0.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

# Se usar o build aqui, com pip, não deve ser usando o arquivo build.sh (e setuptools).
# build:
#   number: 0
#   script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --use-feature=in-tree-build -vv "

requirements:
  build:
    - python
    - setuptools

  host:
    - pip
    - python 3.6
    - requests
    - numpy 1.16 # numpy version specified in conda_build_config.yaml
    #- setuptools
    #- pycep_correios

  run:
    - python

about:
  home: https://github.com/traquitanas/arrebol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Testes do GitAction
  description: |
    Teste do Pacote
  doc_url: https://github.com/traquitanas/arrebol
  dev_url: https://github.com/traquitanas/arrebol
